apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: standard #minikube default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi