#SERVICE- NODE API
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
  namespace: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: nodejs-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mongodb
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      
      volumes:
      - name: shared-volume
        emptyDir: {}

      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "touch /var/www/html/logs/application.log"]
        volumeMounts:
        - name: shared-volume
          mountPath: "/var/www/html/logs"

      containers:
      - name: nodejs-app
        image: brunoteleginski/nodejs-application
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_HOST
          value: "mongo-db"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USER
          value: "root"
        - name: MONGODB_PASS
          value: "1234"
        volumeMounts:
        - name: shared-volume
          mountPath: "/var/www/html/logs"
      
      - name: sidecar
        image: busybox
        args: [/bin/sh, -c, 'tail -n+1 -F /logs/application.log']
        volumeMounts:
        - name: shared-volume
          mountPath: "/logs"
