apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  namespace: task2
  labels:
    app: deploy1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy1
  template:
    metadata:
      namespace: task2
      labels:
        app: deploy1
    spec:
      containers:
      - name: node
        image: brunoteleginski/node-session-1
        ports:
        - containerPort: 3001
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

