apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: task2
spec:
  selector:
    app: deploy1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: node
      protocol: TCP
      port: 3001
      targetPort: 3001