apiVersion: v1
kind: Pod
metadata:
  name: pod-test-1
  labels:
    name: pod-test
spec:
  containers:
  - name: container
    image: brunoteleginski/node-session-1
    ports:
    - containerPort: 3001