apiVersion: v1
kind: Pod
metadata:
  name: pod-empty-dir
spec:
  containers:
  - name: container1
    image: alpine
    command: ['sh', '-c', 'echo "ola amigos  from container 1" >> /shared-dir/container1.txt; sleep 36000']
    volumeMounts:
    - mountPath: "/shared-dir"
      name: shared-volume

  - name: container2
    image: nginx
    volumeMounts:
    - mountPath: "/shared-dir"
      name: shared-volume

  volumes:
  - name: shared-volume
    emptyDir: {}